# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_R=3.3.2
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "kp7jNwEyP3y5NFW0gYuawqTRirwBjiqneHlqJ7+yKP74iDIkSRXNa0fepgrCCGlzinrPyQ9hPJjfDvExyjlCIIxLAK5k2+WpwfIWo25Yn7UN+Cxj1juj3XOwy862SRzrHt9rA5id9TvgNY2JOegf7ofgl+lao7Gl/TZxbucr9pM9Y2DlWE6uZYLUOcBVsnYIqmvsJ2+XoU9nMYI93XVTk1kN53lAB2zCFxyZ/SQeo6lkhqiZ3WKm3fXcCEb4f54EEhDT3XOTCnRV5RkBwYTM3VN1R1Wlhve9EPSEc7FI+Gq+PCjKprUmmE9FrD38x8ESZEvfhvnz9D9lE7teZ6r7BbL3UwuOShWqF5urfbKBwzQgu69tsirn1BE4rauTWmxzvoK8+8UrEYc2cg+YmoymP++MSdoTKIg/mj6G+mBWyDTG4n6OV9ReevnnzY2Z1BxidQMiwCkm5RyKjbX4CILd59p4uCaHEHXTly3jjuvZlJ0d8IumJN50k/ZfCAd47k1FowpVg5Zrdx/ZAUcnS+PVooyBwXZp4VwFol6R6dmPbmfnwM5V8lqSYrB2Nrl8nO/JJ8zEQWWfqu5GWUHcOLCuIeXNqVWiSEBEwUOLA1bGXlYE5sq4Ah6YXZXXKoGMyy+VbYBIHvhcbEDRTKx+iXeUH8Su6+Ub2zoLtdfdD5Gakx8="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
