travis:
  secure:
    BINSTAR_TOKEN: kp7jNwEyP3y5NFW0gYuawqTRirwBjiqneHlqJ7+yKP74iDIkSRXNa0fepgrCCGlzinrPyQ9hPJjfDvExyjlCIIxLAK5k2+WpwfIWo25Yn7UN+Cxj1juj3XOwy862SRzrHt9rA5id9TvgNY2JOegf7ofgl+lao7Gl/TZxbucr9pM9Y2DlWE6uZYLUOcBVsnYIqmvsJ2+XoU9nMYI93XVTk1kN53lAB2zCFxyZ/SQeo6lkhqiZ3WKm3fXcCEb4f54EEhDT3XOTCnRV5RkBwYTM3VN1R1Wlhve9EPSEc7FI+Gq+PCjKprUmmE9FrD38x8ESZEvfhvnz9D9lE7teZ6r7BbL3UwuOShWqF5urfbKBwzQgu69tsirn1BE4rauTWmxzvoK8+8UrEYc2cg+YmoymP++MSdoTKIg/mj6G+mBWyDTG4n6OV9ReevnnzY2Z1BxidQMiwCkm5RyKjbX4CILd59p4uCaHEHXTly3jjuvZlJ0d8IumJN50k/ZfCAd47k1FowpVg5Zrdx/ZAUcnS+PVooyBwXZp4VwFol6R6dmPbmfnwM5V8lqSYrB2Nrl8nO/JJ8zEQWWfqu5GWUHcOLCuIeXNqVWiSEBEwUOLA1bGXlYE5sq4Ah6YXZXXKoGMyy+VbYBIHvhcbEDRTKx+iXeUH8Su6+Ub2zoLtdfdD5Gakx8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
